window.propertyList={
	"-webkit-align-content": ["flex-start", "flex-end", "center", "stretch", "space-around", "space-between"],
	"-webkit-align-items": ["flex-start", "flex-end", "center", "stretch", "baseline"],
	"-webkit-align-self": ["flex-start", "flex-end", "center", "stretch", "baseline"],
	"-webkit-animation": ["animationframes 2s ease 0s 1 normal none running", "animationframes 2s ease 0s 1 normal none running, keyframes 2s ease-in-out 0.5s 1 alternate forwards paused"],
	"-webkit-animation-delay": ["2s", "-1.5s", "2s, -1.5s"],
	"-webkit-animation-direction": ["normal", "alternate", "alternate-reverse", "reverse", "normal, reverse"],
	"-webkit-animation-duration": ["0s", "800ms", "2s", "2.5s", "800ms, 2.5s"],
	"-webkit-animation-fill-mode": ["none", "forwards", "backwards", "both", "forwards, both"],
	"-webkit-animation-iteration-count": ["infinite", "2", "3.4", "infinite, 3.4"],
	"-webkit-animation-name": ["none", "animationframes", "animationframes, keyframes"],
	"-webkit-animation-play-state": ["running", "paused", "running, paused"],
	"-webkit-animation-timing-function": ["linear", "ease", "ease-in", "ease-out", "ease-in-out", "cubic-bezier(0.42, 0, 0.58, 0.9)", "cubic-bezier(0.6, -0.5, 0.4, 1.4)", "steps(2)", "steps(2, end)", "steps(2, start)", "step-start", "step-end", "linear, ease-in-out"],
	"-webkit-app-region": ["drag", "no-drag"],
	"-webkit-appearance": ["none"],
	"-webkit-aspect-ratio": ["from-dimensions", "from-intrinsic", "auto", "1/2", "2/1", "1.5/2", "2/1.5"],
	"-webkit-backface-visibility": ["visible", "hidden"],
	"-webkit-background-clip": ["padding-box", "border-box", "content-box", "text"],
	"-webkit-background-composite": ["border", "clear", "copy", "destination-atop", "destination-in", "destination-out", "destination-over", "highlight", "padding", "plus-darker", "plus-lighter", "source-atop", "source-in", "source-out", "source-over", "xor"],
	"-webkit-background-origin": ["padding-box", "border-box", "content-box"],
	"-webkit-background-size": ["auto", "cover", "contain", "100px", "50%", "100px, 50%", "100px 50%"],
	"-webkit-border-after": ["1px solid #f00", "1px dashed red"],
	"-webkit-border-after-color": ["red", "#f00", "rgb(255,0,0)", "rgba(255,0,0,0.8)"],
	"-webkit-border-after-style": ["dotted", "dashed", "double", "groove", "hidden", "inset", "none", "outset", "ridge", "solid"],
	"-webkit-border-after-width": ["1px", "2px"],
	"-webkit-border-before": ["1px solid #f00", "1px dashed red"],
	"-webkit-border-before-color": ["red", "#f00", "rgb(255,0,0)", "rgba(255,0,0,0.8)"],
	"-webkit-border-before-style": ["dotted", "dashed", "double", "groove", "hidden", "inset", "none", "outset", "ridge", "solid"],
	"-webkit-border-before-width": ["1px", "2px"],
	"-webkit-border-end": ["1px solid #f00", "1px dashed red"],
	"-webkit-border-end-color": ["red", "#f00", "rgb(255,0,0)", "rgba(255,0,0,0.8)"],
	"-webkit-border-end-style": ["dotted", "dashed", "double", "groove", "hidden", "inset", "none", "outset", "ridge", "solid"],
	"-webkit-border-end-width": ["1px", "2px"],
	"-webkit-border-fit": ["lines", "border"],
	"-webkit-border-horizontal-spacing": ["10px"],
	"-webkit-border-image": ["url(http://www.example.com/foo.png)", "url(http://www.example.com/foo.png) 10 round repeat", "url(http://www.example.com/foo.png) 20% repeat stretch", "url(http://www.example.com/foo.png) 10% 20% round stretch"],
	"-webkit-border-image-outset": ["5px", "auto"],
	"-webkit-border-image-repeat": ["repeat", "stretch", "round"],
	"-webkit-border-image-source": ["url(http://www.example.com/foo.png)", "-webkit-linear-gradient(black, transparent)"],
	"-webkit-border-image-slice": ["10", "10 12", "10 12 14", "10 12 14 16"],
	"-webkit-border-image-width": ["auto", "100px", "100%", "100"],
	"-webkit-border-vertical-spacing": ["10px"],
	"-webkit-border-radius":["2px", "50%", "2px / 4px", "20% / 50%", "2px 4px 8px 16px"],
	"-webkit-border-start": ["1px solid #f00", "1px dashed red"],
	"-webkit-border-start-color": ["red", "#f00", "rgb(255,0,0)", "rgba(255,0,0,0.8)"],
	"-webkit-border-start-style": ["dotted", "dashed", "double", "groove", "hidden", "inset", "none", "outset", "ridge", "solid"],
	"-webkit-border-start-width": ["1px", "2px"],
	"-webkit-box-align": ["start", "end", "center", "baseline", "stretch"],
	"-webkit-box-decoration-break": ["slice", "clone"],
	"-webkit-box-direction": ["normal", "reverse"],
	"-webkit-box-flex-group": ["1", "10"],
	"-webkit-box-flex": ["2", "3.4"],
	"-webkit-box-lines": ["single", "multiple"],
	"-webkit-box-ordinal-group": ["1", "2"],
	"-webkit-box-orient": ["horizontal", "vertical"],
	"-webkit-box-pack": ["start", "center", "end", "justify"],
	"-webkit-box-reflect": ["none", "above", "below", "left", "right", "above 10px", "below 10%", "left 0 url(http://www.example.com/foo.png)"],
	"-webkit-box-shadow": ["none", "1px 1px 2px 1px red", "1px 1px 2px -1px red", "1px 1px 2px 1px red inset", "1px 1px 2px 1px red, 1px 1px 2px 1px red"],
	"-webkit-box-sizing": ["content-box", "border-box"],
	"-webkit-column-axis": ["vertical", "horizontal"],
	"-webkit-column-break-after": ["always", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "left", "right", "page", "region"],
	"-webkit-column-break-before": ["always", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "left", "right", "page", "region"],
	"-webkit-column-break-inside": ["auto", "avoid"],
	"-webkit-column-count": ["auto", "2"],
	"-webkit-column-gap": ["normal", "10px"],
	"-webkit-column-progression": [],
	"-webkit-column-rule": ["1px solid red"],
	"-webkit-column-rule-color": ["red", "currentcolor", "-webkit-activelink", "-webkit-focus-ring-color", "-webkit-link", "-webkit-text"],
	"-webkit-column-rule-style": ["dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge", "solid"],
	"-webkit-column-rule-width": ["10px", "thin", "medium", "thick"],
	"-webkit-column-span": ["all", "none"],
	"-webkit-column-width": ["100px", "auto"],
	"-webkit-columns": ["200px", "3"],
	"-webkit-filter": ["none", "blur(1px)", "brightness(50%)", "contrast(50%)", "grayscale(50%)", "hue-rotate(80deg)", "invert(50%)", "opacity(50%)", "saturate(50%)", "sepia(50%)", "drop-shadow(1px 1px 2px red)", "drop-shadow(-1px -1px 2px red)", "blur(1px) opacity(50%)", "url(svg_path)"],
	"-webkit-flex": ["none", "auto", "1 2 auto"],
	"-webkit-flex-basis": ["auto", "0"],
	"-webkit-flex-direction": ["row", "row-reverse", "column", "column-reverse"],
	"-webkit-flex-grow": ["0", "2"],
	"-webkit-flex-shrink": ["0", "2", "0.5"],
	"-webkit-flex-wrap": ["nowrap", "wrap", "wrap-reverse"],
	"-webkit-flow-from": [],
	"-webkit-flow-into": [],
	"-webkit-font-kerning": ["auto", "normal", "none"],
	"-webkit-font-size-delta": ["0", "2px", "1em"],
	"-webkit-font-smoothing": ["none", "subpixel-antialiased", "antialiased"],
	"-webkit-font-variant-ligatures": ["none", "normal", "common-ligatures", "no-common-ligatures", "discretionary-ligatures", "no-discretionary-ligatures", "historical-ligatures", "no-historical-ligatures", "contextual", "no-contextual"],
	"-webkit-hyphenate-character": ["'auto'", "'&amp;shy;'", "'\\2010'", "'\\00AD'", "'\\2022'"],
	"-webkit-justify-content": ["flex-start", "flex-end", "center", "space-between", "space-around"],
	"-webkit-line-break": ["auto", "loose", "normal", "strict", "after-white-space"],
	"-webkit-line-box-contain": ["inline", "block", "glyphs", "replaced", "block inline", "inline replaced", "block replaced", "glyphs replaced", "block inline replaced"],
	"-webkit-line-clamp": ["2", "6"],
	"-webkit-locale": ["auto", "en", "en-US", "en-GB", "not-a-locale"],
	"-webkit-marquee": ["ahead small infinite slow alternate", "forwards medium 2 200px/2s scroll"],
	"-webkit-marquee-direction": ["ahead", "auto", "backwards", "down", "forwards", "left", "reverse", "right", "up"],
	"-webkit-marquee-increment": ["20%", "20px", "small", "medium", "large"],
	"-webkit-marquee-repetition": ["infinite", "2"],
	"-webkit-marquee-speed": ["200px/2s", "slow", "normal", "fast"],
	"-webkit-marquee-style": ["alternate", "none", "scroll", "slide"],
	"-webkit-mask-box-image": ["url(http://www.example.com/foo.png)", "url(http://www.example.com/foo.png) 100 round", "url(http://www.example.com/foo.png) 80% repeat", "url(http://www.example.com/foo.png) 100 200 round stretch", "url(http://www.example.com/foo.png) 80% repeat round"],
	"-webkit-mask-box-image-outset": ["5px", "auto"],
	"-webkit-mask-box-image-repeat": ["repeat", "stretch", "round"],
	"-webkit-mask-box-image-source": ["url(http://www.example.com/foo.png)", "-webkit-linear-gradient(black, transparent)"],
	"-webkit-mask-box-image-slice": ["100", "100 200", "100 200 300", "100 200 240 300", "100 fill", "100 200 fill", "100 200 300 fill", "100 200 240 300 fill"],
	"-webkit-mask-box-image-width": ["auto", "100px", "100%", "100"],
	"-webkit-mask-clip": ["border", "padding", "content", "text"],
	"-webkit-mask-composite": ["clear", "copy", "source-over", "source-in", "source-out", "source-atop", "destination-over", "destination-in", "destination-out", "destination-atop", "xor"],
	"-webkit-mask-image": ["url(http://www.example.com/foo.png)", "-webkit-linear-gradient(black, transparent)"],
	"-webkit-mask-origin": ["padding", "border", "content"],
	"-webkit-mask-position": ["50%", "20px", "50% 20%", "20px 40px", "left top", "center center", "right bottom"],
	"-webkit-mask-position-x": ["50%", "20px", "left", "center", "right"],
	"-webkit-mask-position-y": ["50%", "20px", "top", "center", "bottom"],
	"-webkit-mask-repeat": ["repeat", "repeat-x", "repeat-y", "space", "round", "no-repeat"],
	"-webkit-mask-repeat-x": ["repeat", "space", "round", "no-repeat"],
	"-webkit-mask-repeat-y": ["repeat", "space", "round", "no-repeat"],
	"-webkit-mask-size": ["auto", "contain", "cover", "20px", "20%", "20px 20px", "30% 20%"],
	"-webkit-max-logical-height":["90%", "50px"],
	"-webkit-max-logical-width":["90%", "500px"],
	"-webkit-min-logical-height":["90%", "50px"],
	"-webkit-min-logical-width":["90%", "500px"],
	"-webkit-nbsp-mode": ["normal", "space"],
	"-webkit-padding-start": ["20px", "20%"],
	"-webkit-perspective": ["none", "400", "400px"],
	"-webkit-perspective-origin": ["20%", "20px", "20px 40px", "left", "center", "right", "top", "bottom", "left center", "right bottom", "center top"],
	"-webkit-perspective-origin-x": ["20%", "20px", "left", "center", "right"],
	"-webkit-perspective-origin-y": ["20%", "20px", "top", "center", "bottom"],
	"-webkit-print-color-adjust": ["economy", "exact"],
	"-webkit-rtl-ordering": ["logical", "visual"],
	"-webkit-ruby-position": ["before", "after"],
	"-webkit-tap-highlight-color": ["rgba(0, 0, 0, 0.4)", "transparent"],
	"-webkit-text-combine": ["none", "horizontal"],
	"-webkit-text-decorations-in-effect": ["underline", "overline", "line-through", "blink", "none"],
	"-webkit-text-emphasis": ["red", "triangle", "filled red", "dot #f00", "open currentcolor", "red filled sesame", "sesame filled red"],
	"-webkit-text-emphasis-color": ["red", "#f00", "currentcolor"],
	"-webkit-text-emphasis-position": ["under", "over"],
	"-webkit-text-emphasis-style": ["none", "filled", "open", "dot", "circle", "double-circle", "triangle", "sesame"],
	"-webkit-text-fill-color": ["orange", "red", "transparent", "rgba(0, 0, 0, 0.4)"],
	"-webkit-text-orientation": ["mixed", "upright", "sideways-right", "sideways-left", "sideways", "use-glyph-orientation"],
	"-webkit-text-security": ["none", "circle", "disc", "square"],
	"-webkit-text-size-adjust": ["none", "auto", "120%"],
	"-webkit-text-stroke": ["0.4px", "1px", "0.4px red", "1px red"],
	"-webkit-text-stroke-width": ["0.4px", "1px"],
	"-webkit-text-stroke-color": ["orange", "red", "transparent", "rgba(0, 0, 0, 0.4)"],
	"-webkit-transform": ["none", "matrix(1, 0, 0, 1, 0, 0)", "translate(20px)", "translate(20px, 20px)", "translateX(20px)", "translateY(20px)", "rotate(20deg)", "scale(1)", "scale(1, 2)", "scaleX(1)", "scaleY(2)", "skew(10deg)", "skew(10deg, 20deg)", "skewX(10deg)", "skewY(10deg)", "matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 20, 10, 0, 1)", "matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 20px, 10px, 0, 1)", "translate3d(10px, 10px, 10px)", "translateZ(10px)", "rotate3d(1, 1, 0, 20deg)","scale3d(2, 2, 2)", "scaleZ(2)", "perspective(500px)"],
	"-webkit-transform-origin": ["20%", "20px","left", "center", "right", "top", "bottom", "20% 30%", "20px 40px", "left top", "right bottom", "center center", "center top 20px"],
	"-webkit-transform-origin-x": ["20%", "20px","left", "center", "right"],
	"-webkit-transform-origin-y": ["20%", "20px","top", "center", "bottom"],
	"-webkit-transform-origin-z": ["20px"],
	"-webkit-transform-style": ["flat", "preserve-3d"],
	"-webkit-transition": ["none","all 1s linear 1s", "width 2.4s ease-in-out -0.5s"],
	"-webkit-transition-delay": ["1s", "-0.5s", "1s, 1s", "1s, -0.5s"],
	"-webkit-transition-duration": ["1s", "2.4s"],
	"-webkit-transition-property": ["none", "all", "padding", "transform", "opacity"],
	"-webkit-transition-timing-function": ["linear", "ease", "ease-in", "ease-out", "ease-in-out", "cubic-bezier(0.42, 0, 0.58, 0.9)", "cubic-bezier(0.6, -0.5, 0.4, 1.4)"],
	"-webkit-user-drag": ["auto", "element", "none"],
	"-webkit-user-modify": ["read-only", "read-write", "read-write-plaintext-only"],
	"-webkit-user-select": ["auto", "none", "text"],
	"-webkit-wrap-flow": ["auto", "both", "start", "end", "maximum", "clear"],
	"-webkit-wrap-margin": ["100px", "20%"],
	"-webkit-wrap-through": ["none", "wrap"],
	"-webkit-writing-mode": ["horizontal-tb", "vertical-rl", "vertical-lr"]
}